# Generated by Django 2.2.16 on 2021-04-09 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210409_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 23, 24, 33, 176630), verbose_name='date published'),
        ),
    ]
